---
- name: Check if software is installed on macOS and Windows
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - software_list.yml

  tasks:

    - name: Check software installation on macOS
      command: brew list --cask {{ item.macos }}
      register: macos_check
      changed_when: false
      failed_when: macos_check.rc not in [0, 1]
      ignore_errors: yes
      loop: "{{ software_list }}"
      when: ansible_system == "Darwin" and item.macos != ""

    - name: Check software installation on Windows using winget
      command: winget list "{{ item.windows }}"
      register: winget_check
      changed_when: false
      failed_when: winget_check.rc not in [0, 1]
      ignore_errors: yes
      loop: "{{ software_list }}"
      when: ansible_system == "Win32NT" and item.windows != ""

    - name: Display installed software (macOS)
      debug:
        msg: "{{ item.item.name }} is installed on macOS"
      when: item.rc == 0
      loop: "{{ macos_check.results }}"
      when: ansible_system == "Darwin"

    - name: Display installed software (Windows)
      debug:
        msg: "{{ item.item.name }} is installed on Windows"
      when: item.rc == 0
      loop: "{{ winget_check.results }}"
      when: ansible_system == "Win32NT"
